env_vars:
  MAYA_UI_LANGUAGE: en_US
  MAYA_DISABLE_CLIC_IPM: '1'
  MAYA_SKIP_BLOCKCHECK: '1'
  PYTHONDONTWRITEBYTECODE: '1'
  MAYA_PLUG_IN_PATH: ''
  MAYA_MODULE_PATH: ''
paths:
  PYTHONPATH:
  - P:/dev/smartlibrary/scripts
path: C:/Program Files/Autodesk/Maya2026/bin/maya.exe
icon: ''
