env_vars:
  MAYA_UI_LANGUAGE: en_US
  MAYA_DISABLE_CLIC_IPM: '1'
  MAYA_SKIP_BLOCKCHECK: '1'
  PYTHONDONTWRITEBYTECODE: '1'
paths:
  MAYA_PLUG_IN_PATH:
  - D:/smartlibrary/maya/plug-ins/ngskintools2/Contents/plug-ins/2026
  MAYA_MODULE_PATH:
  - D:/smartlibrary/maya/modules/mgear_5.1.0
  PYTHONPATH:
  - P:/dev/smartlibrary/scripts
path: C:/Program Files/Autodesk/Maya2026/bin/maya.exe
icon: ''
