name: asset
version: 1

quality_profiles:
  FAST:
    model:
      default: proxy
      characters: low
      env: proxy
      prop: proxy
    look: low
    rig: layout

  WORK:
    model:
      default: proxy
      characters: low
      env: proxy
      prop: proxy
    look: low
    rig: anim

  FINAL:
    model:
      default: render
      characters: high
      env: render
      prop: render
    look: high
    rig: anim

viewport:
  background: bbox
  textures: low

fallbacks:
  look:
    high: low
  rig:
    anim: layout
