from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
import os
from pathlib import Path
import re
import shutil
from dataclasses import replace

from smartlib.apps.shot_manager import SequenceIdentity, ShotIdentity, ShotManagerService
from smartlib.core.config_loader import ProjectConfig
from smartlib.core.metadata import read_json
from smartlib.core.versioning import format_version, parse_version
from smartlib.apps.review_build_manager.orchestrator import SceneBuildOrchestrator
from smartlib.apps.smart_sequence_builder.service import SmartSequenceBuilderService


MOV_EXTENSIONS = {".mov", ".mp4"}


@dataclass(frozen=True)
class ReviewOutput:
    version: str
    directory: str
    scene: str = ""
    movie: str = ""
    updated: str = ""
    state: str = "MISSING"


@dataclass(frozen=True)
class ReviewShotStatus:
    identity: ShotIdentity
    state: str
    output_version: str
    output_label: str
    last_review: str
    thumbnail: str
    comment: str
    source_version: str
    message: str
    outputs: tuple[ReviewOutput, ...] = field(default_factory=tuple)


class ReviewBuildManagerService:
    """Resolve review inputs, outputs, and the background Maya runtime."""

    def __init__(self, project_config: ProjectConfig):
        self.project_config = project_config
        self.shots = ShotManagerService(project_config)
        self.orchestrator = SceneBuildOrchestrator(self.shots)
        self.sequence_builder = SmartSequenceBuilderService(project_config)

    def asset_context_profiles(self) -> list[str]:
        try:
            from smartlib.apps.asset_manager.context import AssetContextService

            profiles = AssetContextService(self.project_config).quality_profiles("asset")
        except (FileNotFoundError, KeyError, TypeError, ValueError):
            profiles = []
        ordered = []
        for profile in [*profiles, "WORK", "REND", "FINAL", "FAST"]:
            value = str(profile).strip().upper()
            if value and value not in ordered:
                ordered.append(value)
        return ordered

    def build_plan(
        self,
        identity: ShotIdentity,
        *,
        mode: str = "WORK STAGE",
        department: str = "anim",
        task: str = "",
        input_policy: str = "GENERATE MISSING",
        overrides: dict | None = None,
    ):
        return self.orchestrator.plan(
            identity,
            requested_mode=mode,
            department=department,
            task=task,
            input_policy=input_policy,
            overrides=overrides,
        )

    def ensure_stage_input(
        self,
        identity: ShotIdentity,
        *,
        policy: str = "GENERATE MISSING",
        overrides: dict | None = None,
        comment: str = "",
    ) -> Path:
        policy = str(policy or "GENERATE MISSING").strip().upper()
        current = self.shots.latest_anim_input(identity)
        if policy == "USE EXISTING":
            if not current:
                raise FileNotFoundError(
                    f"Animation Input Package was not found for {identity.code}."
                )
            return current
        if current and policy == "GENERATE MISSING":
            current_data = read_json(current, {}) or {}
            current_overrides = current_data.get("overrides") or {}
            requested_overrides = overrides or {}
            relevant_keys = {
                "context",
                "camera",
                "layout_overlay",
                "use_placements",
                "exclude_cast",
                "cast_contexts",
            }
            current_relevant = {
                key: current_overrides.get(key)
                for key in relevant_keys
                if key in current_overrides
            }
            requested_relevant = {
                key: requested_overrides.get(key)
                for key in relevant_keys
                if key in requested_overrides
            }
            if current_relevant == requested_relevant:
                return current
        result = self.shots.build_anim_input_package_for_shot(
            identity,
            comment=comment or "Generated by Review Build Manager",
            overrides=overrides,
        )
        return result.anim_input

    def sequence_build_plan(
        self,
        identity: SequenceIdentity,
        *,
        recipe: str = "",
        virtual_camera_take: str = "",
        enabled_inputs: dict[str, bool] | None = None,
        **kwargs,
    ):
        plan = self.orchestrator.plan_sequence(identity, **kwargs)
        recipe_plan = self.sequence_builder.plan(
            identity.episode,
            identity.sequence,
            recipe or self.default_sequence_recipe(),
            virtual_camera_take=virtual_camera_take,
            enabled=enabled_inputs,
        )
        from smartlib.apps.review_build_manager.orchestrator import BuildValidation

        recipe_validations = tuple(
            BuildValidation(
                "ERROR" if row.state == "ERROR" else "WARNING" if row.state == "WARNING" else "INFO",
                f"SEQUENCE_{row.key.upper()}",
                row.detail,
            )
            for row in recipe_plan.validation
            if row.state in {"ERROR", "WARNING"}
        )
        validations = tuple(plan.validations) + recipe_validations
        state = (
            "BLOCKED" if any(row.severity == "ERROR" for row in validations)
            else "WARNING" if any(row.severity == "WARNING" for row in validations)
            else plan.state
        )
        return replace(plan, state=state, validations=validations)

    def sequence_recipes(self) -> list[str]:
        return list(self.sequence_builder.recipes())

    def default_sequence_recipe(self) -> str:
        recipes = self.sequence_recipes()
        return recipes[0] if recipes else "Mocap + Virtual Camera"

    def sequence_recipe_plan(
        self,
        identity: SequenceIdentity,
        *,
        recipe: str = "",
        virtual_camera_take: str = "",
        enabled_inputs: dict[str, bool] | None = None,
    ):
        return self.sequence_builder.plan(
            identity.episode,
            identity.sequence,
            recipe or self.default_sequence_recipe(),
            virtual_camera_take=virtual_camera_take,
            enabled=enabled_inputs,
        )

    def ensure_sequence_stage_input(
        self,
        identity: SequenceIdentity,
        *,
        policy: str = "GENERATE MISSING",
        department: str = "layout",
        overrides: dict | None = None,
        comment: str = "",
    ) -> Path:
        policy = str(policy or "GENERATE MISSING").strip().upper()
        current = self.shots.latest_sequence_stage_input(identity, department)
        if policy == "USE EXISTING":
            if not current:
                raise FileNotFoundError(
                    f"Sequence Input Package was not found for {identity.code}."
                )
            return current
        if current and policy == "GENERATE MISSING":
            return current
        return self.shots.build_sequence_stage_input(
            identity,
            department=department,
            comment=comment or "Generated by Review Build Manager",
            overrides=overrides,
        )

    @property
    def project_name(self) -> str:
        return str(
            getattr(self.project_config, "project_name", "")
            or self.project_config.config_dir.name
        )

    def scan(
        self,
        *,
        mode: str = "WORK STAGE",
        department: str = "anim",
        task: str = "main",
        generate_review: bool = False,
        overrides: dict | None = None,
    ) -> list[ReviewShotStatus]:
        return [
            self.shot_status(
                identity,
                mode=mode,
                department=department,
                task=task,
                generate_review=generate_review,
                overrides=overrides,
            )
            for identity in self.shots.list_shots()
        ]

    @staticmethod
    def apply_generate_review_requirement(
        status: ReviewShotStatus,
        enabled: bool,
    ) -> ReviewShotStatus:
        """Update only the optional MOV requirement from cached scan data."""

        if status.state in {"MISSING", "DIRTY"}:
            return status
        matching_review = next(
            (
                output for output in status.outputs
                if output.version == status.output_version
                and output.movie
                and Path(output.movie).is_file()
            ),
            None,
        )
        missing_message = "Construct is current; Generate Review MOV is not available."
        if enabled and not matching_review:
            if status.state == "UP TO DATE":
                return replace(status, state="READY", message=missing_message)
            return status
        if status.message == missing_message:
            return replace(
                status,
                state="UP TO DATE",
                message=(
                    "Construct and Animation Curves are current; review was generated."
                    if enabled and matching_review
                    else "Construct and Animation Curves are current."
                ),
            )
        return status

    def build_contents(
        self,
        identity: ShotIdentity,
        *,
        default_context: str = "WORK",
        cast_contexts: dict[str, str] | None = None,
        excluded_cast: list[str] | None = None,
        representation: str = "project",
    ) -> list[dict]:
        context_map = {
            str(key): str(value).upper()
            for key, value in (cast_contexts or {}).items()
        }
        construct = self.shots.resolved_construct(
            identity,
            cast_contexts=context_map,
            exclude_cast=excluded_cast,
            representation=representation,
        )
        rows = []
        for component in construct.get("components") or []:
            source = dict(component.get("source") or {})
            name = str(component.get("name") or "")
            component_type = str(component.get("component_type") or "rig")
            is_cast = component_type == "rig"
            is_usd = component_type == "usd"
            context = (
                context_map.get(
                    name,
                    str(source.get("context") or default_context or "WORK").upper(),
                )
                if is_cast
                else "payload" if is_usd else ""
            )
            asset = str(source.get("asset") or "")
            variant = str(source.get("variant") or "default")
            asset_root = self.shots.find_asset_root(asset)
            variant_root = asset_root / variant if asset_root else None
            latest_path = None
            if is_cast and variant_root and variant_root.is_dir():
                latest_path = self.shots.asset_publish_resolver.resolve_context(
                    variant_root,
                    context,
                    version="latest",
                )
            path = Path(str(component.get("path") or ""))
            official = str(component.get("version") or "")
            latest = latest_path.parent.name if latest_path else (
                path.parent.name if is_usd and path.is_file() else ""
            )
            enabled = bool(component.get("enabled", True))
            state = "EXCLUDED" if not enabled else "MISSING"
            if enabled and (path.is_file() or path.is_dir()):
                state = "UPDATE AVAILABLE" if latest and latest != official else "READY"
            rows.append(
                {
                    "cast_key": name,
                    "component_key": [component_type, name, str(source.get("field") or "")],
                    "type": "rig" if is_cast else component_type,
                    "asset": asset,
                    "role": str(source.get("role") or ""),
                    "variant": variant,
                    "context": context,
                    "official": official,
                    "latest": latest,
                    "state": state,
                    "required": bool(component.get("required", True)),
                    "enabled": enabled,
                    "note": str(component.get("note") or ""),
                    "component": dict(component),
                }
            )
        return rows

    def save_build_contents(self, identity: ShotIdentity, rows: list[dict]) -> Path:
        return self.shots.write_construct(
            identity,
            {"components": [dict(row.get("component") or {}) for row in rows]},
        )

    def construct_diff(
        self,
        identity: ShotIdentity,
        *,
        current: dict | None = None,
        desired: dict | None = None,
        cast_contexts: dict[str, str] | None = None,
        excluded_cast: list[str] | None = None,
        representation: str = "project",
    ) -> list[dict]:
        """Compare a saved Construct with freshly resolved published inputs."""
        current = current or self.shots.load_construct(identity)
        desired = desired or self.shots.construct_from_stage_inputs(
            identity,
            cast_contexts=cast_contexts,
            exclude_cast=excluded_cast,
            representation=representation,
        )

        def key(component: dict) -> tuple[str, str, str]:
            source = component.get("source") or {}
            return (
                str(component.get("component_type") or "").lower(),
                str(component.get("name") or ""),
                str(source.get("field") or source.get("kind") or ""),
            )

        old = {key(row): dict(row) for row in current.get("components") or []}
        new = {key(row): dict(row) for row in desired.get("components") or []}
        changes = []
        for component_key in sorted(set(old) | set(new)):
            before = old.get(component_key)
            after = new.get(component_key)
            change = "UNCHANGED"
            if before is None:
                change = "ADDED"
            elif after is None:
                change = "REMOVED"
            else:
                fields = [
                    name for name in ("version", "path", "enabled", "mode")
                    if before.get(name) != after.get(name)
                ]
                if str((before.get("source") or {}).get("context") or "") != str(
                    (after.get("source") or {}).get("context") or ""
                ):
                    fields.append("context")
                if fields:
                    change = "UPDATED"
            component = after or before or {}
            asset_status = self._construct_asset_status(component)
            changes.append({
                "key": list(component_key),
                "change": change,
                "severity": "ERROR" if asset_status == "omit" else (
                    "INFO" if change == "UNCHANGED" else "WARNING"
                ),
                "asset_status": asset_status,
                "selected": change != "UNCHANGED" and asset_status != "omit",
                "before": before or {},
                "after": after or {},
            })
        return changes

    def _construct_asset_status(self, component: dict) -> str:
        if str(component.get("component_type") or "").lower() != "rig":
            return ""
        source = component.get("source") or {}
        asset_root = self.shots.find_asset_root(str(source.get("asset") or ""))
        if not asset_root:
            return "missing"
        metadata = read_json(asset_root / "asset.json", {}) or {}
        variant = str(source.get("variant") or "default")
        variant_data = read_json(asset_root / variant / "variant.json", {}) or {}
        return str(variant_data.get("status") or metadata.get("status") or "").strip().lower()

    def list_constructs(self, identity: ShotIdentity, department: str, task: str) -> list[dict]:
        root = (
            self.shots.shot_root(identity)
            / "output"
            / "scene_build"
            / str(department or "main").strip().lower()
            / str(task or "main").strip().lower()
        )
        rows = []
        if not root.is_dir():
            return rows
        for version_dir in sorted(root.glob("v*"), reverse=True):
            if not version_dir.is_dir():
                continue
            manifest = read_json(version_dir / "build_manifest.json", {}) or {}
            validation = read_json(version_dir / "validation.json", {}) or {}
            scene = next(iter(sorted(version_dir.glob("*.m[ab]"))), None)
            state = str(validation.get("state") or validation.get("status") or "VERIFYING").upper()
            validation_results = [
                dict(item)
                for item in (validation.get("results") or [])
                if isinstance(item, dict)
            ]
            rows.append(
                {
                    "version": version_dir.name,
                    "directory": str(version_dir),
                    "state": state,
                    "scene": str(scene or ""),
                    "updated": datetime.fromtimestamp(version_dir.stat().st_mtime).strftime("%Y-%m-%d %H:%M"),
                    "components": len(manifest.get("components") or manifest.get("resolved_assets") or []),
                    "validation_results": validation_results,
                }
            )
        return rows

    def list_sequence_constructs(
        self, identity: SequenceIdentity, department: str, task: str
    ) -> list[dict]:
        root = (
            self.shots.sequence_workspace_root(identity.episode, identity.sequence)
            / "output" / "scene_build"
            / str(department or "main").strip().lower()
            / str(task or "main").strip().lower()
        )
        rows = []
        for version_dir in sorted(root.glob("v*"), reverse=True) if root.is_dir() else []:
            if not version_dir.is_dir():
                continue
            manifest = read_json(version_dir / "build_manifest.json", {}) or {}
            validation = read_json(version_dir / "validation.json", {}) or {}
            scene = next(iter(sorted(version_dir.glob("*.m[ab]"))), None)
            rows.append({
                "version": version_dir.name,
                "state": str(validation.get("state") or validation.get("status") or "VERIFYING").upper(),
                "scene": str(scene or ""),
                "updated": datetime.fromtimestamp(version_dir.stat().st_mtime).strftime("%Y-%m-%d %H:%M"),
                "shots": list(manifest.get("shots") or []),
            })
        return rows

    def next_output_version(self, identity: ShotIdentity) -> str:
        versions = self.list_outputs(identity)
        number = max((parse_version(row.version) or 0 for row in versions), default=0) + 1
        return format_version(number)

    def next_construct_version(
        self,
        identity: ShotIdentity,
        department: str,
        task: str,
    ) -> str:
        root = (
            self.shots.shot_root(identity)
            / "output"
            / "scene_build"
            / str(department or "main").strip().lower()
            / str(task or "main").strip().lower()
        )
        numbers = [
            parse_version(path.name) or 0
            for path in root.glob("v*")
            if path.is_dir()
        ] if root.is_dir() else []
        return format_version(max(numbers, default=0) + 1)

    def next_sequence_output_version(self, identity: SequenceIdentity) -> str:
        root = (
            self.shots.sequence_workspace_root(identity.episode, identity.sequence)
            / "output"
            / "review"
            / "layout"
        )
        numbers = [
            parse_version(path.name) or 0
            for path in root.glob("v*")
            if path.is_dir()
        ] if root.is_dir() else []
        return format_version(max(numbers, default=0) + 1)

    def next_sequence_construct_version(
        self,
        identity: SequenceIdentity,
        department: str,
        task: str,
    ) -> str:
        root = (
            self.shots.sequence_workspace_root(identity.episode, identity.sequence)
            / "output"
            / "scene_build"
            / str(department or "main").strip().lower()
            / str(task or "main").strip().lower()
        )
        numbers = [
            parse_version(path.name) or 0
            for path in root.glob("v*")
            if path.is_dir()
        ] if root.is_dir() else []
        return format_version(max(numbers, default=0) + 1)

    def resolve_mayapy(self) -> Path:
        configured = os.environ.get("SMARTPIPELINE_MAYAPY")
        if configured and Path(configured).is_file():
            return Path(configured)
        candidates = []
        preferred = self.project_config.config_dir / "software_maya2024.yml"
        if preferred.is_file():
            candidates.append(preferred)
        candidates.extend(
            path
            for path in sorted(self.project_config.config_dir.glob("software_maya*.yml"))
            if path not in candidates
        )
        for config_path in candidates:
            data = self.project_config.load(config_path.name)
            maya_path = Path(str(data.get("path") or ""))
            if maya_path.suffix.lower() in {".bat", ".cmd"} and maya_path.is_file():
                text = maya_path.read_text(encoding="utf-8-sig", errors="ignore")
                match = re.search(
                    r"^\s*set\s+MAYAINSTPATH\s*=\s*(.+?)\s*$",
                    text,
                    flags=re.IGNORECASE | re.MULTILINE,
                )
                if match:
                    install_root = Path(match.group(1).strip().strip('"'))
                    mayapy = install_root / "bin" / "mayapy.exe"
                    if mayapy.is_file():
                        return mayapy
            mayapy = maya_path.with_name("mayapy.exe")
            if mayapy.is_file():
                return mayapy
        raise FileNotFoundError(
            "mayapy.exe was not resolved. Set SMARTPIPELINE_MAYAPY or configure software_maya*.yml."
        )

    def shot_status(
        self,
        identity: ShotIdentity,
        *,
        mode: str = "WORK STAGE",
        department: str = "anim",
        task: str = "main",
        generate_review: bool = False,
        overrides: dict | None = None,
    ) -> ReviewShotStatus:
        if str(mode or "WORK STAGE").upper() == "WORK STAGE":
            return self._work_stage_status(
                identity,
                department=department,
                task=task,
                generate_review=generate_review,
                overrides=overrides or {},
            )
        source = self.shots.latest_animation_package_path(identity)
        source_version = source.parent.name if source else ""
        outputs = tuple(self.list_outputs(identity))
        latest_output = outputs[0] if outputs else None
        shot_data = self.shots.load_shot(identity)
        thumbnail = self.shots.shot_root(identity) / "thumbnail.jpg"

        if not source:
            state = "MISSING"
            message = "Animation Package is missing."
        elif not latest_output:
            state = "READY"
            message = "No review output has been generated."
        elif self._is_dirty(source, latest_output):
            state = "DIRTY"
            message = "Published inputs are newer than the last review build."
        elif not latest_output.movie:
            state = "READY"
            message = "Review scene exists, but the output movie is missing."
        else:
            state = "UP TO DATE"
            message = "Output movie matches the current Animation Package."

        output_version = latest_output.version if latest_output else ""
        if latest_output and latest_output.movie:
            output_label = output_version
        elif latest_output:
            output_label = f"{output_version} / MOV missing"
        else:
            output_label = "-"
        return ReviewShotStatus(
            identity=identity,
            state=state,
            output_version=output_version,
            output_label=output_label,
            last_review=latest_output.updated if latest_output else "-",
            thumbnail=str(thumbnail) if thumbnail.is_file() else "",
            comment=str(shot_data.get("status") or ""),
            source_version=source_version,
            message=message,
            outputs=outputs,
        )

    def _work_stage_status(
        self,
        identity: ShotIdentity,
        *,
        department: str,
        task: str,
        generate_review: bool,
        overrides: dict,
    ) -> ReviewShotStatus:
        """Evaluate WORK STAGE from Construct inputs, never Animation Package."""

        desired = self.shots.resolved_construct(
            identity,
            cast_contexts=dict(overrides.get("cast_contexts") or {}),
            exclude_cast=list(overrides.get("exclude_cast") or []),
            representation=str(overrides.get("representation") or "project"),
        )
        components = [
            row for row in (desired.get("components") or [])
            if isinstance(row, dict) and bool(row.get("enabled", True))
        ]
        def component_available(row: dict) -> bool:
            value = str(row.get("path") or "").strip()
            return bool(value) and Path(value).exists()

        missing = [
            str(row.get("name") or row.get("component_type") or "input")
            for row in components
            if bool(row.get("required", True))
            and not component_available(row)
        ]
        missing_curves = []
        curve_names = {
            str(row.get("name") or "")
            for row in components
            if str(row.get("component_type") or "").lower() == "animation_curve"
        }
        if str(department or "").lower() == "anim":
            cast_data = self.shots.load_cast(identity)
            if not (cast_data.get("cast") or {}):
                cast_data = self.shots.load_sequence_cast(
                    identity.episode, identity.sequence
                )
            excluded = {str(value) for value in overrides.get("exclude_cast") or []}
            missing_curves = [
                str(cast_key)
                for cast_key, entry in (cast_data.get("cast") or {}).items()
                if bool((entry or {}).get("required", True))
                and str((entry or {}).get("role") or "").strip().upper()
                not in {"BG", "BGA", "ENV", "BACKGROUND", "SET"}
                and str(cast_key) not in excluded
                and str(cast_key) not in curve_names
            ]

        constructs = self.list_constructs(identity, department, task)
        latest = constructs[0] if constructs else None
        manifest = (
            read_json(
                Path(str(latest.get("directory") or "")) / "build_manifest.json",
                {},
            ) or {}
            if latest else {}
        )
        recorded = manifest.get("construct") or {"components": []}
        changes = self.construct_diff(identity, current=recorded, desired=desired)
        changed = [row for row in changes if row.get("change") != "UNCHANGED"]

        curve_versions = sorted({
            str(row.get("version") or "")
            for row in components
            if str(row.get("component_type") or "").lower() == "animation_curve"
            and str(row.get("version") or "")
        })
        source_version = ", ".join(curve_versions)
        if missing or missing_curves:
            state = "MISSING"
            details = []
            if missing:
                details.append("required inputs: " + ", ".join(missing))
            if missing_curves:
                details.append("Animation Curves: " + ", ".join(missing_curves))
            message = "Missing " + "; ".join(details) + "."
        elif not latest:
            state = "READY"
            message = "Construct inputs and Animation Curves are ready."
        elif changed:
            state = "DIRTY"
            names = [
                str((row.get("after") or row.get("before") or {}).get("name") or "input")
                for row in changed
            ]
            message = "Construct inputs changed: " + ", ".join(dict.fromkeys(names)) + "."
        elif generate_review and not Path(
            str(manifest.get("review_movie") or "")
        ).is_file():
            state = "READY"
            message = "Construct is current; Generate Review MOV is not available."
        else:
            state = "UP TO DATE"
            message = (
                "Construct and Animation Curves are current; review was generated."
                if generate_review
                else "Construct and Animation Curves are current."
            )

        shot_data = self.shots.load_shot(identity)
        thumbnail = self.shots.shot_root(identity) / "thumbnail.jpg"
        version = str(latest.get("version") or "") if latest else ""
        outputs = tuple(self.list_outputs(identity))
        latest_review = outputs[0] if outputs else None
        return ReviewShotStatus(
            identity=identity,
            state=state,
            output_version=version,
            output_label=version or "-",
            last_review=(
                latest_review.updated
                if latest_review else str(latest.get("updated") or "-") if latest else "-"
            ),
            thumbnail=str(thumbnail) if thumbnail.is_file() else "",
            comment=str(shot_data.get("status") or ""),
            source_version=source_version,
            message=message,
            outputs=outputs,
        )

    def list_outputs(self, identity: ShotIdentity) -> list[ReviewOutput]:
        root = (
            self.shots.shot_root(identity)
            / "output"
            / "review"
            / "animation"
        )
        rows: list[ReviewOutput] = []
        for version_dir in root.glob("v*") if root.is_dir() else []:
            if not version_dir.is_dir() or parse_version(version_dir.name) is None:
                continue
            scene = self._first_file(version_dir, {".ma", ".mb"})
            movie = self._first_file(version_dir, MOV_EXTENSIONS)
            manifest = version_dir / "build_manifest.json"
            manifest_data = read_json(manifest, {}) or {}
            recorded_scene = Path(str(manifest_data.get("scene") or ""))
            if not scene and recorded_scene.is_file():
                scene = recorded_scene
            timestamps = [
                path.stat().st_mtime
                for path in (scene, movie, manifest)
                if path and path.is_file()
            ]
            updated = (
                datetime.fromtimestamp(max(timestamps)).strftime("%Y-%m-%d %H:%M")
                if timestamps
                else ""
            )
            state = "COMPLETE" if movie else ("SCENE ONLY" if scene else "MISSING")
            rows.append(
                ReviewOutput(
                    version=version_dir.name,
                    directory=str(version_dir),
                    scene=str(scene) if scene else "",
                    movie=str(movie) if movie else "",
                    updated=updated,
                    state=state,
                )
            )
        return sorted(
            rows,
            key=lambda row: parse_version(row.version) or 0,
            reverse=True,
        )

    def accept_output_to_work(
        self,
        identity: ShotIdentity,
        output: ReviewOutput,
        *,
        department: str = "anim",
        task: str = "",
        option: str = "main",
    ) -> Path:
        source = Path(output.scene)
        if not source.is_file():
            raise FileNotFoundError("The selected output has no generated scene to accept.")
        task = task or self.shots.shot_tasks(department)[0]
        current_rows = self.shots.list_shot_work_files(
            identity,
            department=department,
            option=option,
            tool_name="maya",
            task=task,
        )
        current = current_rows[0].path if current_rows else None
        destination = self.shots.next_shot_work_path(
            identity,
            department,
            current_path=current,
            next_version=bool(current),
            option=option,
            tool_name="maya",
            ext=source.suffix.lstrip("."),
            task=task,
        )
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)
        self.shots.write_shot_work_metadata(
            destination,
            identity,
            department,
            option=option,
            task=task,
            comment=f"Accepted from Review Build {output.version}",
        )
        return destination

    @staticmethod
    def _first_file(root: Path, extensions: set[str]) -> Path | None:
        matches = sorted(
            (
                path
                for path in root.rglob("*")
                if path.is_file() and path.suffix.lower() in extensions
            ),
            key=lambda path: path.stat().st_mtime,
            reverse=True,
        )
        return matches[0] if matches else None

    @staticmethod
    def _is_dirty(source: Path, output: ReviewOutput) -> bool:
        output_dir = Path(output.directory)
        build_manifest = read_json(output_dir / "build_manifest.json", {}) or {}
        recorded = Path(str(build_manifest.get("animation_manifest") or ""))
        if recorded and recorded.as_posix().lower() != source.as_posix().lower():
            return True
        comparison = Path(output.movie or output.scene)
        if not comparison.is_file():
            return True
        if source.stat().st_mtime > comparison.stat().st_mtime:
            return True
        review_spec = Path(str(build_manifest.get("review_spec") or ""))
        return review_spec.is_file() and review_spec.stat().st_mtime > comparison.stat().st_mtime
