anchors:
  smartpipeline_root: P:/dev/smartlibrary
  smartpipeline_tools: P:/dev/smarttools

runtime:
  python: "{smartpipeline_tools}/python/Scripts/python.exe"

tools:
  ffmpeg:
    path: "{smartpipeline_tools}/ffmpeg/ffmpeg.exe"
  usdcat:
    path: "{smartpipeline_root}/tools/usd/usdcat.bat"
  usdview:
    path: "{smartpipeline_root}/tools/usd/usdview.bat"
  openrv:
    path: "{smartpipeline_tools}/openrv/rv.exe"

third_party:
  python:
    path: "{smartpipeline_tools}/third_party/python"
  nodegraphqt:
    path: "{smartpipeline_tools}/third_party/NodeGraphQt-PySide6"
