@echo off
if not defined SMARTPIPELINE_ROOT set "SMARTPIPELINE_ROOT=%~dp0.."
if not defined SMARTLIBRARY_ROOT set "SMARTLIBRARY_ROOT=%SMARTPIPELINE_ROOT%"

if not defined SMARTPIPELINE_TOOLS set "SMARTPIPELINE_TOOLS=%SMARTPIPELINE_ROOT%\..\smarttools"
if not defined SMARTPIPELINE_STUDIO_CONFIG_DIR set "SMARTPIPELINE_STUDIO_CONFIG_DIR=%SMARTPIPELINE_ROOT%\..\smartprojects"
if not defined SMARTPIPELINE_STUDIO_CONFIG set "SMARTPIPELINE_STUDIO_CONFIG=%SMARTPIPELINE_STUDIO_CONFIG_DIR%\studio.yml"
if not defined PROJECT_CONFIG_DIR set "PROJECT_CONFIG_DIR=%SMARTPIPELINE_STUDIO_CONFIG_DIR%\config\STKB"

set "PYTHONPATH=%SMARTPIPELINE_ROOT%\packages;%SMARTPIPELINE_ROOT%;%PYTHONPATH%"

if not defined SMARTPIPELINE_PYTHON set "SMARTPIPELINE_PYTHON=%SMARTPIPELINE_TOOLS%\python\Scripts\python.exe"
if not exist "%SMARTPIPELINE_PYTHON%" set "SMARTPIPELINE_PYTHON=%SMARTPIPELINE_TOOLS%\python\python.exe"
if not exist "%SMARTPIPELINE_PYTHON%" set "SMARTPIPELINE_PYTHON=%SMARTPIPELINE_ROOT%\runtime\python\Scripts\python.exe"
if not exist "%SMARTPIPELINE_PYTHON%" set "SMARTPIPELINE_PYTHON=%SMARTPIPELINE_ROOT%\runtime\python\python.exe"
if not exist "%SMARTPIPELINE_PYTHON%" set "SMARTPIPELINE_PYTHON=python"
