anchors:
  project_name: NEWPROJ
  project_root: D:/Projects/NEWPROJ
  fps: 24
  resolution:
  - 1920
  - 1080
enabled_softwares: []
shot_depts:
- anim
asset_depts:
- model
- rig
templates:
  art_root: '{project_root}/art'
  assets_root: '{project_root}/assets'
  editorial_root: '{project_root}/editorial'
  prepro_root: '{project_root}/prepro'
  sequences_root: '{project_root}/sequences'
  shots_root: '{project_root}/shots'
  setting_root: '{project_root}/settings'
  delivery_root: '{project_root}/delivery'
  library_root: '{project_root}/library'
  users_root: '{project_root}/users'
  workspace_root: '{project_root}/workspace'
  tool_dir: '{setting_root}/tools'
  storyboard_dir: '{prepro_root}/storyboards'
  reference_dir: '{prepro_root}/reference'
