anchors:
  project_name: ELCD
  project_root: I://ELCD
  fps: 24
  resolution:
  - 1280
  - 720
enabled_softwares:
- usdview
- start_maya2024
shot_depts:
- layout
- anim
- fx
- light
- comp
asset_depts:
- model
- rig
- look
templates:
  assets_root: '{project_root}/assets'
  editorial_root: '{project_root}/editorial'
  production_root: '{project_root}/production'
  sequences_root: '{project_root}/sequences'
  shots_root: '{project_root}/shots'
  setting_root: '{project_root}/settings'
  delivery_root: '{project_root}/delivery'
  library_root: '{project_root}/library'
  tool_dir: '{setting_root}/tools'
  contract_dir: '{production_root}/contracts'
  storyboard_dir: '{production_root}/storyboards'
  reference_dir: '{production_root}/reference'
