anchors:
  project_name: ELCD
  project_root: D:/Projects/ELCD
  fps: 24
  resolution:
  - 1280
  - 720
enabled_softwares:
- usdview
- start_maya2024
shot_depts:
- layout
- anim
- fx
- light
- comp
asset_depts:
- model
- rig
- look
templates:
  assets_root: '{project_root}/assets'
  editorial_root: '{project_root}/editorial'
  sequences_root: '{project_root}/sequences'
  shots_root: '{project_root}/shots'
